### ISSUE TITLE
sdrtrunk with Windows/aarch64 support

### ISSUE THREAD

**Issue by DSheirer** [JVital2013/armsdr.com#1]
I added experimental support to sdrtrunk for windows arm64 but I don't have a way to test it.  Feel free to add it to your list of compatible SDR software.  If you're able to test it and find any issues, please let me know.

Release:  https://github.com/DSheirer/sdrtrunk/releases/tag/v0.6.1-beta-3

**Comment by JVital2013** [comment]
Hello @DSheirer!

First off, thanks for working on this! More Windows ARM64 programs are sorely needed for SDRs. Unfortunately, at this time, the SDRTrunk beta listed does not work. It is missing libusb4java:

![image](https://github.com/user-attachments/assets/01a9ec05-cb92-4b16-a22c-3bc402de3bc4)
![image](https://github.com/user-attachments/assets/bfbd5260-e10b-4987-9f02-ce7b0a56965f)

Once this is fixed I can continue evaluation. Thanks again!

**Comment by DSheirer** [comment]
Thanks for testing!  

I ran into the same issue with OSX on aarch64 and it required someone with access to that OS to compile the native libraries.  Is that something that you could do?

Instructions for how to complete it are located here: http://usb4java.org/nativelibs.html  (Unsupported Platforms section).

If not, I'll temporarily disable sdtrunk support until we can find someone that can compile the usb4java native library.

**Comment by JVital2013** [comment]
Yeah, I think I can do that. I'll let you know once I take a look!

**Comment by JVital2013** [comment]
Hi @DSheirer,

I just opened two issues on your GitHub.

- https://github.com/DSheirer/sdrtrunk/issues/2081 contains the necessary jar to fix the issue I mentioned, so you can work it into your build process. Just dropping it into the `lib` folder of the current beta works for me. Let me know if you need anything else on this end!
- There's also a minor issue where it attempts to load the SDRPlay library from the wrong location. The issue for that is here: https://github.com/DSheirer/sdrtrunk/issues/2082

Thanks again for your work on this platform!

**Comment by DSheirer** [comment]
sdrtrunk updated with libusb native library support for windows aarch64 from this issue: https://github.com/DSheirer/sdrtrunk/issues/2081

**Comment by JVital2013** [comment]
Thanks @DSheirer! Unfortunately, the latest nightly is not working at all, while the last beta did work when I slipped in the libusb4java I built and libusb-1.0.dll manually. Here's the new error (looks like it's not finding libusb):

```
2024-11-05 07:07:19.028 INFO  i.g.d.s.t.m.TunerManager - Discovering tuners ...  [10MB/28MB 35%]
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.usb4java.LibUsb.getApiVersion()'
        at org.usb4java.LibUsb.getApiVersion(Native Method)
        at io.github.dsheirer.source.tuner.manager.TunerManager.start(TunerManager.java:113)
        at io.github.dsheirer.gui.SDRTrunk.<init>(SDRTrunk.java:193)
        at io.github.dsheirer.gui.SDRTrunk.main(SDRTrunk.java:937)
```

**Comment by JVital2013** [comment]
Let me know if I need to statically link libusb to libusb4java. It didn't by default, but I suppose it could be coaxed

**Comment by DSheirer** [comment]
Is libusb.dll installed in the /windows/system32/ directory on your machine?

**Comment by JVital2013** [comment]
Looks like that's not the issue anyway, but - libusb-1.0.dll should never be in the Windows folder, despite what I've seen some old programs do (grumble grumble...) The only thing there is WinUSB, configured by Zadig (or manually on Arm64).

For the real problem: they failed to mention this in their build instructions, but https://github.com/usb4java/libusb4java/blob/master/dists/win32/build.bat clearly builds libusb4java statically linked to libusb, which I did not do. I built it dynamically. I've verified this by running dumpbin on the official build, which I should have done before.

I'll re-build libusb4java statically linked to libusb so we don't have this problem. Sorry about that!

**Comment by DSheirer** [comment]
No worries!  Thanks again for doing this!  I have limited/no experience on the non-Java languages and would be quite lost trying to figure that out.

**Comment by JVital2013** [comment]
I'm happy to help! Let's try this again:

- https://github.com/DSheirer/sdrtrunk/issues/2084

**Comment by JVital2013** [comment]
Works great - thanks for the support! I've added SDR Trunk to the site.

![image](https://github.com/user-attachments/assets/134cf003-1a61-45c9-95c0-934a514732a6)

**Comment by DSheirer** [comment]
Great news!  Thanks for all your help!
